services:
  config-server-service:
    build: ../config-server-service
    container_name: config-server-service
    ports:
      - "9091:9091"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - booker-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9091/actuator/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  discovery-server-service:
    build: ../discovery-server-service
    container_name: discovery-server-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_SERVER_URL=http://config-server-service:9091
    ports:
      - "9090:9090"
    depends_on:
      config-server-service:
        condition: service_started
    networks:
      - booker-network

  gateway-service:
    build: ../gateway-service
    container_name: gateway-service
    ports:
      - "9098:9098"
    depends_on:
      config-server-service:
        condition: service_started
      discovery-server-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_SERVER_URL=http://config-server-service:9091
    networks:
      - booker-network

  auth-service:
    build: ../auth-service
    container_name: auth-service
    depends_on:
      config-server-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_SERVER_URL=http://config-server-service:9091
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    ports:
      - "9093:9093"
    networks:
      - booker-network

  product-service:
    build: ../product-service
    container_name: product-service
    depends_on:
      config-server-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_SERVER_URL=http://config-server-service:9091
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    ports:
      - "9094:9094"
    networks:
      - booker-network

  booking-service:
    build: ../booking-service
    container_name: booking-service
    depends_on:
      config-server-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_SERVER_URL=http://config-server-service:9091
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    ports:
      - "9095:9095"
    networks:
      - booker-network

  payment-service:
    build: ../payment-service
    container_name: payment-service
    depends_on:
      config-server-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_SERVER_URL=http://config-server-service:9091
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    ports:
      - "9096:9096"
    networks:
      - booker-network

  seat-service:
    build: ../seat-service
    container_name: seat-service
    depends_on:
      config-server-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CONFIG_SERVER_URL=http://config-server-service:9091
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    ports:
      - "9097:9097"
    networks:
      - booker-network

networks:
  booker-network:
    external: true
