spring:
  application:
    name: booking-service
  
  datasource:
    url: jdbc:postgresql://booker-booking-db:5432/booker-booking-db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: booker-kafka:29092
    schema:
      registry:
        url: "http://booker-schema-registry:8081"
    consumer:
      group-id: booking-service-4
      auto-offset-reset: "earliest"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      properties:
        specific:
          avro:
            reader: "true"
        schema:
          registry:
            url: "http://booker-schema-registry:8081"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://booker-schema-registry:8081"

  data:
    redis:
      host: booker-redis-container
      port: 6379
      database: 1
  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9097

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:9090/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      booking-service-booking-details:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED